export const birds = [
  "American Crow",
  "American Goldfinch",
  "American Kestrel",
  "American Robin",
  "American White Pelican",
  "American Woodcock",
  "Bald Eagle",
  "Baltimore Oriole",
  "Barn Swallow",
  "Barred Owl",
  "Belted Kingfisher",
  "Black-capped Chickadee",
  "Blue Jay",
  "Blue-gray Gnatcatcher",
  "Brown Creeper",
  "Brown Thrasher",
  "Brown-headed Cowbird",
  "Canada Goose",
  "Cedar Waxwing",
  "Chipping Sparrow",
  "Common Grackle",
  "Common Merganser",
  "Common Yellowthroat",
  "Cooper's Hawk",
  "Dark-eyed Junco",
  "Double-crested Cormorant",
  "Downy Woodpecker",
  "Eastern Bluebird",
  "Eastern Phoebe",
  "Eastern Towhee",
  "European Starling",
  "Gray Catbird",
  "Great Blue Heron",
  "Great Egret",
  "Great Horned Owl",
  "Green Heron",
  "Hairy Woodpecker",
  "House Finch",
  "House Sparrow",
  "Indigo Bunting",
  "Killdeer",
  "Mallard",
  "Mourning Dove",
  "Northern Cardinal",
  "Northern Flicker",
  "Northern House Wren",
  "Northern Mockingbird",
  "Pileated Woodpecker",
  "Pine Siskin",
  "Purple Finch",
  "Red-bellied Woodpecker",
  "Red-breasted Nuthatch",
  "Red-headed Woodpecker",
  "Red-tailed Hawk",
  "Red-winged Blackbird",
  "Ring-billed Gull",
  "Rose-breasted Grosbeak",
  "Ruby-throated Hummingbird",
  "Sandhill Crane",
  "Scarlet Tanager",
  "Song Sparrow",
  "Tree Swallow",
  "Turkey Vulture",
  "White-breasted Nuthatch",
  "White-throated Sparrow",
  "Wild Turkey",
  "Wood Duck",
  "Yellow Warbler",
];
